apiVersion: v1
kind: List
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    generateName: master-
    labels:
      set: master
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        address: 172.17.8.101
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    generateName: worker-
    labels:
      set: worker
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        address: 172.17.8.102
